package servlets;
import db.DBConnection; import javax.servlet.annotation.WebServlet; import javax.servlet.http.*; import java.io.*; import java.sql.*; import java.sql.Types;
@WebServlet("/signup") public class SignupServlet extends HttpServlet { protected void doPost(HttpServletRequest req,HttpServletResponse resp)throws IOException{HttpSession s=req.getSession(false);if(s==null||s.getAttribute("userId")==null){resp.sendRedirect("login.jsp");return;}int eventId;try{eventId=Integer.parseInt(req.getParameter("eventId"));}catch(Exception e){resp.sendRedirect("index.jsp");return;}String action=req.getParameter("action");try{if("cancel".equals(action))cancel((Integer)s.getAttribute("userId"),eventId);else signup((Integer)s.getAttribute("userId"),eventId);s.setAttribute("flashSuccess","cancel".equals(action)?"Signup cancelled. Waitlist updated automatically.":"Event signup updated.");}catch(SQLException e){s.setAttribute("flashError","Could not update signup: "+e.getMessage());}String back=req.getParameter("returnTo");if("my-events".equals(back))resp.sendRedirect("my-events");else if("events.jsp".equals(back))resp.sendRedirect("events.jsp");else resp.sendRedirect("index.jsp");}
 private void signup(int uid,int eid)throws SQLException{try(Connection c=DBConnection.getConnection()){c.setAutoCommit(false);try{
  String old=null;Integer sid=null;try(PreparedStatement p=c.prepareStatement("SELECT Signup_ID,Status FROM Signups WHERE Student_ID=? AND Event_ID=? FOR UPDATE")){p.setInt(1,uid);p.setInt(2,eid);try(ResultSet r=p.executeQuery()){if(r.next()){sid=r.getInt(1);old=r.getString(2);}}}if("registered".equals(old)||"waitlisted".equals(old)){c.rollback();return;}
  int cap,count;try(PreparedStatement p=c.prepareStatement("SELECT Capacity,(SELECT COUNT(*) FROM Signups WHERE Event_ID=? AND Status='registered') cnt FROM Events WHERE Event_ID=? AND Is_Cancelled=0 FOR UPDATE")){p.setInt(1,eid);p.setInt(2,eid);try(ResultSet r=p.executeQuery()){if(!r.next()){c.rollback();return;}cap=r.getInt(1);count=r.getInt(2);}}
  String status=count<cap?"registered":"waitlisted";Integer pos=null;if("waitlisted".equals(status)){try(PreparedStatement p=c.prepareStatement("SELECT COALESCE(MAX(Waitlist_Position),0)+1 FROM Signups WHERE Event_ID=? AND Status='waitlisted'")){p.setInt(1,eid);try(ResultSet r=p.executeQuery()){r.next();pos=r.getInt(1);}}}
  if(sid==null){try(PreparedStatement p=c.prepareStatement("INSERT INTO Signups(Student_ID,Event_ID,Status,Waitlist_Position) VALUES(?,?,?,?)")){p.setInt(1,uid);p.setInt(2,eid);p.setString(3,status);if(pos==null)p.setNull(4,Types.INTEGER);else p.setInt(4,pos);p.executeUpdate();}}else{try(PreparedStatement p=c.prepareStatement("UPDATE Signups SET Status=?,Waitlist_Position=?,Signed_Up_At=CURRENT_TIMESTAMP WHERE Signup_ID=?")){p.setString(1,status);if(pos==null)p.setNull(2,Types.INTEGER);else p.setInt(2,pos);p.setInt(3,sid);p.executeUpdate();}}c.commit();
 }catch(SQLException e){c.rollback();throw e;}}}
 private void cancel(int uid,int eid)throws SQLException{try(Connection c=DBConnection.getConnection()){c.setAutoCommit(false);try{String status=null;Integer pos=null;int sid=0;try(PreparedStatement p=c.prepareStatement("SELECT Signup_ID,Status,Waitlist_Position FROM Signups WHERE Student_ID=? AND Event_ID=? FOR UPDATE")){p.setInt(1,uid);p.setInt(2,eid);try(ResultSet r=p.executeQuery()){if(r.next()){sid=r.getInt(1);status=r.getString(2);pos=(Integer)r.getObject(3);}}}if(sid==0||"cancelled".equals(status)){c.rollback();return;}try(PreparedStatement p=c.prepareStatement("UPDATE Signups SET Status='cancelled',Waitlist_Position=NULL WHERE Signup_ID=?")){p.setInt(1,sid);p.executeUpdate();}if("registered".equals(status)){Integer next=null;try(PreparedStatement p=c.prepareStatement("SELECT Signup_ID FROM Signups WHERE Event_ID=? AND Status='waitlisted' ORDER BY Waitlist_Position LIMIT 1 FOR UPDATE")){p.setInt(1,eid);try(ResultSet r=p.executeQuery()){if(r.next())next=r.getInt(1);}}if(next!=null){try(PreparedStatement p=c.prepareStatement("UPDATE Signups SET Status='registered',Waitlist_Position=NULL WHERE Signup_ID=?")){p.setInt(1,next);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE Signups SET Waitlist_Position=Waitlist_Position-1 WHERE Event_ID=? AND Status='waitlisted'")){p.setInt(1,eid);p.executeUpdate();}}}else if(pos!=null){try(PreparedStatement p=c.prepareStatement("UPDATE Signups SET Waitlist_Position=Waitlist_Position-1 WHERE Event_ID=? AND Status='waitlisted' AND Waitlist_Position>?")){p.setInt(1,eid);p.setInt(2,pos);p.executeUpdate();}}c.commit();}catch(SQLException e){c.rollback();throw e;}}}
}
